### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by PcChip** [iOrange/rtxON#11]
I noticed some conversation that says your tutorial is outdated, thought you might want to know so you can update if needed
  
https://www.reddit.com/r/vulkan/comments/jzvpfi/how_to_assign_object_ids/

**Comment by iOrange** [comment]
Hi!

Thanks for bringing it to me.
While I'm trying to keep the code pretty much up-to-date with the latest changes to Vulkan Ray Tracing specs, the "tutorial" itself is outdated for sure, as I wrote it in 2018 when only Nvidia experimental extension existed.

Sincerely,
iOrange
