### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by DistantThunder** [iOrange/rtxON#14]
Hello, tried to run your demo with 

Mesa RADV 21.3.0 on Arch Linux 5.15.x. 

Granted, RADV's RTRT implementation is still fresh and may be lacking but noticed a bunch of stuff I believe is worth checking:

>VUID-VkBufferCreateInfo-size-00912(ERROR / SPEC): msgNum: 2085897310 - Validation Error: [ VUID-VkBufferCreateInfo-size-00912 ] Object 0: handle = 0x560ac6bfb0a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7c54445e | vkCreateBuffer: parameter pCreateInfo->size (= 0) is not greater than 0 The Vulkan spec states: size must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-size-00912)
    Objects: 1
        [0] 0x560ac6bfb0a0, type: 3, name: NULL
VUID-VkMemoryAllocateInfo-allocationSize-00638(ERROR / SPEC): msgNum: 830614613 - Validation Error: [ VUID-VkMemoryAllocateInfo-allocationSize-00638 ] Object 0: handle = 0x560ac6bfb0a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x31822c55 | vkAllocateMemory: allocationSize is 0. The Vulkan spec states: allocationSize must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.2-khr-extensions/html/vkspec.html#VUID-VkMemoryAllocateInfo-allocationSize-00638)
    Objects: 1
        [0] 0x560ac6bfb0a0, type: 3, name: NULL
VUID-vkBindBufferMemory-memoryOffset-01031(ERROR / SPEC): msgNum: -143326275 - Validation Error: [ VUID-vkBindBufferMemory-memoryOffset-01031 ] Object 0: handle = 0x27d60e0000000019, type = VK_OBJECT_TYPE_DEVICE_MEMORY; Object 1: handle = 0xd10d270000000018, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xf77503bd | In vkBindBufferMemory(), attempting to bind VkDeviceMemory 0x27d60e0000000019[] to VkBuffer 0xd10d270000000018[], memoryOffset=0x0 must be less than the memory allocation size 0x0. The Vulkan spec states: memoryOffset must be less than the size of memory (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkBindBufferMemory-memoryOffset-01031)
    Objects: 2
        [0] 0x27d60e0000000019, type: 8, name: NULL
        [1] 0xd10d270000000018, type: 9, name: NULL
VUID-VkBufferCreateInfo-size-00912(ERROR / SPEC): msgNum: 2085897310 - Validation Error: [ VUID-VkBufferCreateInfo-size-00912 ] Object 0: handle = 0x560ac6bfb0a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7c54445e | vkCreateBuffer: parameter pCreateInfo->size (= 0) is not greater than 0 The Vulkan spec states: size must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-size-00912)
    Objects: 1
        [0] 0x560ac6bfb0a0, type: 3, name: NULL
VUID-VkMemoryAllocateInfo-allocationSize-00638(ERROR / SPEC): msgNum: 830614613 - Validation Error: [ VUID-VkMemoryAllocateInfo-allocationSize-00638 ] Object 0: handle = 0x560ac6bfb0a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x31822c55 | vkAllocateMemory: allocationSize is 0. The Vulkan spec states: allocationSize must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.2-khr-extensions/html/vkspec.html#VUID-VkMemoryAllocateInfo-allocationSize-00638)
    Objects: 1
        [0] 0x560ac6bfb0a0, type: 3, name: NULL
VUID-vkBindBufferMemory-memoryOffset-01031(ERROR / SPEC): msgNum: -143326275 - Validation Error: [ VUID-vkBindBufferMemory-memoryOffset-01031 ] Object 0: handle = 0xcb1c7c000000001b, type = VK_OBJECT_TYPE_DEVICE_MEMORY; Object 1: handle = 0x95a125000000001a, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xf77503bd | In vkBindBufferMemory(), attempting to bind VkDeviceMemory 0xcb1c7c000000001b[] to VkBuffer 0x95a125000000001a[], memoryOffset=0x0 must be less than the memory allocation size 0x0. The Vulkan spec states: memoryOffset must be less than the size of memory (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkBindBufferMemory-memoryOffset-01031)
    Objects: 2
        [0] 0xcb1c7c000000001b, type: 8, name: NULL
        [1] 0x95a125000000001a, type: 9, name: NULL
VUID-vkMapMemory-size-00680(ERROR / SPEC): msgNum: -12089429 - Validation Error: [ VUID-vkMapMemory-size-00680 ] Object 0: handle = 0xcb1c7c000000001b, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xff4787ab | VkMapMemory: Attempting to map memory range of size zero The Vulkan spec states: If size is not equal to VK_WHOLE_SIZE, size must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkMapMemory-size-00680)
    Objects: 1
        [0] 0xcb1c7c000000001b, type: 8, name: NULL
VUID-vkMapMemory-offset-00679(ERROR / SPEC): msgNum: -654128652 - Validation Error: [ VUID-vkMapMemory-offset-00679 ] Object 0: handle = 0xcb1c7c000000001b, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xd902c9f4 | VkMapMemory: Attempting to map memory with an offset of 0x0 which is larger than the total array size 0x0 The Vulkan spec states: offset must be less than the size of memory (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkMapMemory-offset-00679)
    Objects: 1
        [0] 0xcb1c7c000000001b, type: 8, name: NULL

**Comment by iOrange** [comment]
Wow, ok, time to dust-off my Linux machine I guess then :)

**Comment by Seabass247** [comment]
I got the error `allocationSize is 0` and fixed it by changing the file paths at the top of `rtxApp.cpp`:
```
static const String sShadersFolder = "../_data/shaders/";
static const String sScenesFolder = "../_data/scenes/";
static const String sEnvsFolder = "../_data/envs/";
```
Seems that the error was occurring because no mesh data was loaded in as it could not load the .obj files.

**Comment by SparkyTD** [comment]
@iOrange Sorry to bother, but I am getting the same validation errors as OP. Downloaded code from master, followed the instructions and built with Visual Studio 2022. Is there any way to make it work?
