### ISSUE TITLE
vkAcquireNextImageKHR Validation Error

### ISSUE THREAD

**Issue by SparkyTD** [iOrange/rtxON#15]
Hello,

I'm getting this validation error spammed in my console with a solid white window when I try to run the code:

```
VUID-vkAcquireNextImageKHR-swapchain-01802(ERROR / SPEC): msgNum: 1050126472 - Validation Error: 
[ VUID-vkAcquireNextImageKHR-swapchain-01802 ] Object 0: handle = 0xfab64d0000000002, 
type = VK_OBJECT_TYPE_SWAPCHAIN_KHR; | MessageID = 0x3e97a888 | vkAcquireNextImageKHR: 
Application has already previously acquired 1 image from swapchain. Only 1 is available to be acquired using a 
timeout of UINT64_MAX (given the swapchain has 2, and VkSurfaceCapabilitiesKHR::minImageCount is 2). 
The Vulkan spec states: If the number of currently acquired images is greater than the difference between the 
number of images in swapchain and the value of VkSurfaceCapabilitiesKHR::minImageCount as returned by a call to 
vkGetPhysicalDeviceSurfaceCapabilities2KHR with the surface used to create swapchain, timeout must not be 
UINT64_MAX (https://vulkan.lunarg.com/doc/view/1.2.198.1/windows/1.2-extensions/vkspec.html#VUID-vkAcquireNextImageKHR-swapchain-01802)
    Objects: 1
       [0]  0xfab64d0000000002, type: 1000001000, name: NULL
```

I followed the build instructions, built everything with Visual Studio 2022, and the code compiles without any issues. Is there any way I could fix this?

**Comment by iOrange** [comment]
Hi, would you mind sharing your system specs and environment (OS, version) ?

**Comment by SparkyTD** [comment]
Sure!

Windows 11 [10.0.22000.466]
Vulkan SDK 1.2.198.1
Visual Studio 2022 (v143)
RTX 3070

**Comment by iOrange** [comment]
This is interesting, as I can't repro it.
I'm on Win 11 myself, Vulkan SDK 1.2.189.2,  VS 2022, RTX 3080.

Are you generating the solution or opening the folder in VS (using built-in CMake support) ?
Did you set the working directory correctly (the root folder of this project) ?

**Comment by SparkyTD** [comment]
I followed your instructions to generate the VS project. It builds without any errors, the window appears, and the console starts spamming the validation error with a white window. Based on the title bar it "runs" at 320000000.0 FPS.

The working directory is set to the project root directory, where the _data folder is.

**Comment by iOrange** [comment]
Sorry, can't think of a cause of this issue from the top of my mind.
I'll meditate a bit reading Vulkan specs to see if I can find any clues.

**Comment by iOrange** [comment]
Hi, are you on PC or laptop ?
I'm out of ideas so trying my wild guesses now :)

**Comment by SparkyTD** [comment]
I am on PC. My hardware def. supports RT, because I've been able to build and run other RTX samples, such as [this one](https://github.com/GPSnoopy/RayTracingInVulkan).

I haven't spent much time looking at the source, but is the program waiting for all the render/presentation stages to be complete? Based on the validation error message (and the impossibly high FPS) I assume that for some reason the program doesn't wait for the current frame to be finished before requesting the next one from the swap chain.

**Comment by iOrange** [comment]
Well, if I'm reading your validation error correctly - it says that we've grabbed 1 image from swapchain and that left swapchain empty.  Which is a bit crazy tbh as I have not seen this before.
Would you be able to put the breakpoint in `VulkanApp::InitializeSwapchain` to see what's in `surfaceCapabilities` ?

And then in the same method after we do `vkGetSwapchainImagesKHR(mDevice, mSwapchain, &imageCount, nullptr);`, what's `imageCount` value ?

Thanks a lot!

**Comment by SparkyTD** [comment]
Capabilities:
![image](https://user-images.githubusercontent.com/45818400/152043124-4197f28b-416d-423d-af0a-fbb5705606c9.png)

`imageCount` is 2

**Comment by iOrange** [comment]
OMG, thanks a lot for this screenshot!
I was finally able to repro this issue, and it's totally my fault - I'm using `mSettings.resolutionX` and `mSettings.resolutionX` everywhere, and it works as long as there's sufficient screen space.
But in your screenshot I can see that your surface is 1061 in height, and the default settings is 1920*1080, so the actual validation error is:

```VUID-VkSwapchainCreateInfoKHR-imageExtent-01274(ERROR / SPEC): msgNum: 2094043421 - Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x1a2c262ca70, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (1920,1080), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (1920,1061), minImageExtent = (1920,1061), maxImageExtent = (1920,1061). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://vulkan.lunarg.com/doc/view/1.2.198.1/windows/1.2-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
    Objects: 1
       [0]  0x1a2c262ca70, type: 3, name: NULL
```

But the craziest thing is that `vkCreateSwapchainKHR` still returns `VK_SUCCESS` !  So this issue flies under radar and the explodes once we try to present something.

Just submitted 6d6ca71 to fix this issue.
Thanks so much for reporting this and for your patience and cooperation!

**Comment by SparkyTD** [comment]
I'm glad I could help! I'm still trying to learn Vulkan and RT, and this is one of the best projects I could find, that demonstrates Vulkan RT while also keeping it simple.

**Comment by iOrange** [comment]
Thanks for the warm words 😊
I'm closing this issue, but feel free to contact me any time if you have more questions.
