### ISSUE TITLE
Validation error after build and run

### ISSUE THREAD

**Issue by tiantian20007** [iOrange/rtxON#7]
**error log after launch**

VUID-VkBufferCreateInfo-size-00912(ERROR / SPEC): msgNum: 0 - vkCreateBuffer: parameter pCreateInfo->size (= 0) is greater than 0 The Vulkan spec states: size must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-size-00912)
    Objects: 1
       [0] 0x0, type: 9, name: (null)
Validation(ERROR): msg_code: 0:  [ VUID-VkBufferCreateInfo-size-00912 ]  [ VUID-VkBufferCreateInfo-size-00912 ] Object: VK_NULL_HANDLE (Type = 9) | vkCreateBuffer: parameter pCreateInfo->size (= 0) is greater than 0 The Vulkan spec states: size must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-size-00912)
Assertion failed: false && "instancesBuffer.Create", file J:\RTX\rtxON\src\rtxApp.cpp, line 466

**platform**

OS: Windows10
VulkanSDK: 1.1.92.1
GPU: rtx 2070
Compiler: VS2017

**Comment by Reon90** [comment]
I have the same issue.

OS: Windows10 1809
VulkanSDK: 1.1.97
GPU: rtx 2070
Compiler: VS2017

**Comment by iOrange** [comment]
Seems like you're getting this issue since your working directory is wrong, so no assets (scene in this case) were loaded.

I've modified CMakeLists so it'll set the proper debugging directory for the project
a319e82b2e9aef78894d85cb31b7b512ff30432f

**Comment by Reon90** [comment]
@iOrange thank you for your response, it was fixed.
