### ISSUE TITLE
UNASSIGNED-CoreValidation-Shader-DescriptorTypeMismatch - error

### ISSUE THREAD

**Issue by PrzemyslawSagalo** [iOrange/rtxON#8]
Just after lunch the program returns:
`UNASSIGNED-CoreValidation-Shader-DescriptorTypeMismatch(ERROR` / SPEC): msgNum: 0 - Type mismatch on descriptor slot 0.0 (expected ``) but descriptor of type VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV
    Objects: 1
       [0] 0x0, type: 0, name: (null)
Validation(ERROR): msg_code: 0:  [ UNASSIGNED-CoreValidation-Shader-DescriptorTypeMismatch ] Object: VK_NULL_HANDLE (Type = 0) | Type mismatch on descriptor slot 0.0 (expected ``) but descriptor of type `VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV`

Happy triangle is not crated but Chrome teapot and a glass bunny is generated properly.

**Comment by iOrange** [comment]
Sorry, yes, Happy Triangle was written against the preview version of RTX extension, and thus isn't working now :(

It's unfortunate, since I don't have a branch for it so can't fix it.

Never mind this message, I believe it's a validator bug, as it says `(expected ``)` which is nonsense.
