### ISSUE TITLE
Next article plans

### ISSUE THREAD

**Issue by Reon90** [iOrange/rtxON#9]
In the last article, you said that "In the next article we will try to build a hybrid renderer that combines rasterization and ray tracing."

Do you have any plans about that, I think it's quite interesting.

**Comment by iOrange** [comment]
Hi!

Thanks for your interest in my articles.
Yes, I have plans on continuing writing articles about Vulkan Ray Tracing, unfortunately at the moment I don't have enough spare time for that.

But I hope I'll be able to continue soon.
Stay tuned!
